### ISSUE TITLE
Does not work on these texts

### ISSUE THREAD

**Issue by ericwu13** [iliazeus/vscode-ansi#32] opened 2024-07-09 18:30 UTC
I have these texts `b'\r\x1b[mBlablabla\x1b[33mSomethingsomething\n'`, but the extensions does not work. Is there any solution to this?

**Comment by iliazeus** [comment] 2024-08-16 12:51
This extension only works with actual ANSI escapes, and does not understand the backslash-escaped forms used in source code.

(duplicate of #12)

**Closed by iliazeus** 2024-08-16 12:51 UTC
