### ISSUE TITLE
Is it possible to get rid of these excess escape sequences?

### ISSUE THREAD

**Issue by holland11** [iliazeus/vscode-ansi#21] opened 2023-02-14 21:20 UTC
In my `~/.zshrc` I have
```
autoload -U colors
colors

PROMPT="%{$fg[yellow]%}%T %{$fg[cyan]%}%~"$'\n'"%{$fg[yellow]%}> "%{$'\e[00m'%}
```
This produces the output shown here
<img width="312" alt="Screenshot 2023-02-14 at 1 15 35 PM" src="https://user-images.githubusercontent.com/20808409/218864762-51f4746d-cf18-459d-b683-6e807fab0f84.png">

When I log my terminal buffer, this turns into
<img width="637" alt="Screenshot 2023-02-14 at 1 16 17 PM" src="https://user-images.githubusercontent.com/20808409/218864878-bf51f464-d752-41fd-8e14-757f06e767dc.png">

Using the ANSI Colors preview, it now looks like
<img width="591" alt="Screenshot 2023-02-14 at 1 16 51 PM" src="https://user-images.githubusercontent.com/20808409/218864973-7e419fbf-d758-414e-8461-15b43ecaa28e.png">

which is certainly an improvement, but there are quite a few escape sequences still in here that make it hard to read. Is there a way with this extension (or could there be?) or any other way unrelated to this extension that I could conveniently get rid of them all?

**Comment by holland11** [comment] 2023-02-14 23:38
Well I found a tool `ansifilter` that removes all ANSI escape sequences from a text file. This cleans up the log to be readable, but it obviously removes the escape sequences that this extensions uses to add colours. It's the main thing I was after though (clean + readable).

**Comment by iliazeus** [comment] 2023-02-15 02:54
The extension only interprets/hides the `Select Graphic Rendition` escapes. This is by design.

**Comment by iliazeus** [comment] 2023-02-27 09:55
The problem with some escapes showing up in the read-only preview should be fixed in the latest extension version.

**Closed by iliazeus** 2023-02-27 09:55 UTC
